### ISSUE TITLE
Consider enabling autoLaunch by default

### ISSUE THREAD

**Issue by nickmccurdy** [netlify/cli#1200]
**Is your feature request related to a problem? Please describe.**

Many modern tools like create-react-app and Docusaurus automatically launch browsers by default when starting servers. `netlify dev` supports this through `dev.autoLaunch` in `netlify.toml`, but it's hard to find the config option and its documentation.

**Describe the solution you'd like**

`dev.autoLaunch` should default to `true` instead of `false`.

**Describe alternatives you've considered**

1. Leave `autoLaunch` off by default. I'd prefer to avoid this because it's unusual compared to other tools and makes it harder to launch the right server.
2. Only automatically enable `autoLaunch` on certain framework detectors. This could work by hard coding a boolean flag into certain detectors or using config fields like `env: { BROWSER: 'none' }` to guess.

**Can you submit a pull request?**

Yes, but I wanted to get a consensus on if/how this should be implemented first.

**Comment by erezrokah** [comment]
Looks like the default was `autoLaunch: true`, but got:
- Broken in https://github.com/netlify/cli/pull/631
- Fixed in https://github.com/netlify/cli/pull/673
- Broken again in https://github.com/netlify/cli/pull/811/files#diff-8a2f65e3aede3ea9696e546766f50f03R492

The last version the default was `true` is https://github.com/netlify/cli/releases/tag/v2.42.0 and it broke in https://github.com/netlify/cli/releases/tag/v2.43.0

You can test is using

```
npx netlify-cli@v2.42.0 dev
npx netlify-cli@v2.43.0 dev
```
