### ISSUE TITLE
Community report: CLI behaviour does not match containerized behaviour regarding .gitignore files

### ISSUE THREAD

**Issue by PerrySetGo** [netlify/cli#1225]
### Describe the bug

We have a customer report in our Community forums indicating that the behaviour of the CLI and the behaviour of the web app differ in regards to how .gitignore files are treated.

### Steps to reproduce the behavior

Please see the discussion in this thread:
https://community.netlify.com/t/dont-apply-gitignore-rules-to-the-publish-directory/21244/7

### Expected vs actual behavior

It is our (@PerrySetGo , @depadiernos, @rstavchansky ) expectation that the two should work the same 🤷

**Comment by erezrokah** [comment]
Looks like there are 2 different issues in that thread:
1. regarding `. gitignore` behaviour during deploy (unrelated to the CLI).
2. regarding a difference between how our build system deploys the publish directory vs how the CLI deploys the publish directory. It seems the former deploys everything in the publish directory and the latter doesn't upload `**/node_modules` directories (which was already resolved for the user due to a change in Nuxt behaviour).

**Comment by erezrokah** [comment]
Looks like `node_modules` are not ignored in the buildbot:
https://github.com/netlify/open-api/blob/e72e2eb2d7eedf02bccc5916fc0330022f7f823b/go/porcelain/deploy.go#L692
But are ignored in the CLI:
https://github.com/netlify/js-client/blob/55650048fc7fe6288816c1dc172b27024cbd1586/src/deploy/util.js#L11

It makes sense to ignore those in the CLI in some cases, for example when deploying the project directory via:
`netlify deploy --dir .`

**Comment by PerrySetGo** [comment]
i circled back to the community post and thanked them again for their contribution, fyi.

**Comment by erezrokah** [comment]
Still not published yet, will do that today/tomorrow
