### ISSUE TITLE
Deploy edge handlers locally

### ISSUE THREAD

**Issue by mraerino** [netlify/cli#1236]
**Is your feature request related to a problem? Please describe.**

Right now, the edge handler plugin will only put the bundled edge handler into a local directory when running via `netlify build` in the CLI. We need to upload bundled edge handlers when deploying locally.

**Describe the solution you'd like**

`netlify deploy` should detect whether there are bundled edge handlers in `.netlify/edge-handlers`

If there is a manifest & a bundle, it should use the upload method from the edge handler plugin to upload the bundle to the api: https://github.com/netlify/netlify-plugin-edge-handlers/blob/master/src/upload.js

- Read the bundle file and pass the file buffer as `buf`
- Read the manifest and parse it as json, pass the object as `info`
- The access token should be valid for the site that is being deployed to

This should happen after the deploy has been created, but before the deploy is complete (and post-processing starts).

**Describe alternatives you've considered**

The edge handler plugin could upload the bundle directly, but when `netlify build` runs locally, we don't have a deploy object yet.

**Additional context**

API endpoint used by the plugin: https://bitballoon-openapi.netlify.app/external#operation/Edge%20Handlers-create

**Can you submit a pull request?**

Yes, but @erezrokah might be helping with this.

**Comment by erezrokah** [comment]
I did some initial work in https://github.com/netlify/cli/tree/feat/edge_handlers_deploy (it is based on https://github.com/netlify/cli/pull/1240) to add deploying edge handlers using the CLI.
The deploy doesn't work at the moment since we need to deploy edge handlers before the deploy is complete.
The CLI uses a [`deploy` function](https://github.com/netlify/js-client#deploy--await-clientdeploysiteid-builddir-opts) from `js-client` which returns after the deploy is complete.

We can:
1. Have `js-client` handle deploying edge handlers (this is the current pattern for functions).
2. Use the `statusCb` mechanism `js-client` has to hook into deploy events. That would require supporting async callbacks in `js-client.`

**Comment by mraerino** [comment]
third option:
patching js-client to accept a `deployId` parameter in the `deploy` function.
if that is passed it can skip creating the deploy.

that way we could create the deploy ourselves, upload handlers and then trigger the js-client function.

**Comment by mraerino** [comment]
this is what buildbot does, since it will be called with an existing deploy: https://github.com/netlify/open-api/blob/master/go/porcelain/deploy.go#L239-L262

**Comment by mraerino** [comment]
using such a flow can be beneficial because it keeps the code composable and gives long-term flexibility.

**Comment by erezrokah** [comment]
Trying to clarify advantages and disadvantages of each approach:
### Have `js-client` handle deploying edge handlers
Advantages:
- Each consumer of `js-client` could pass `edgeHandlers` as a folder (similar to functions) and have the client handle deployment.
- Small change to the CLI (just passes `edgeHandlers` as a folder).
- Similar to the way the CLI handles deploy at the moment.

Disadvantages:
- Adds more logic to the already long `deploy` `js-client` function.
- Might require adding `https://github.com/netlify/netlify-plugin-edge-handlers` as a dependency  or duplicating https://github.com/netlify/netlify-plugin-edge-handlers/blob/851e827ec7aca41d79ef56fdd931d460fa140e75/src/upload.js#L22
- CLI has less control of the deploy process.

### Use the `statusCb` mechanism `js-client` has to hook into deploy events
Advantages:
- Less code changes to `js-client`.
- There is already an existing mechanism to hook into deploy stages, we just need to extend it.

Disadvantages:
- Looks like the callback mechanism was intended for reporting progress, we might end up abusing it.
- `js-client` consumers would have to duplicate the CLI logic in order to deploy edge handlers.

### Have the CLI create the deploy, upload edge handlers and `js-client` handle files and functions upload
 Advantages:
- Shifts more control over deployment to the CLI.
- Aligns the `js-client` with the `go-client` (which buildbot uses).

Disadvantages:
- Splits the deploy logic between the CLI and `js-client`. The `createSiteDeploy` call would have to be duplicated between the CLI and `js-client` (related to the former).
- `js-client` consumers would have to duplicate the CLI logic in order to deploy edge handlers.

**Comment by erezrokah** [comment]
Following up with an extension of the third option (handling edge handlers deploy in the CLI).
Opened an issue to consider moving all of the deploy logic to the CLI:

**Comment by ehmicky** [comment]
I agree with @mraerino that the following would be great:

> that way the CLI could create the deploy itself, upload handlers and then trigger the js-client/deploy function.

Generally speaking, the `js-client `should be a thin REST client. Any heavier logic, such as Functions or Edge handlers uploading and hashing, should be moved to the CLI instead, that users can use for that purpose. I think #157 would be a great solution to this problem. We could then easily add the Edge handlers upload and hashing logic on top of it :+1:
