### ISSUE TITLE
Feat: define encrypted/secret environment variables

### ISSUE THREAD

**Issue by DirtyF** [netlify/cli#134]
**- Do you want to request a *feature* or report a *bug*?**

It's a feature !

**- What is the current behavior?**

Not being able to store secret credentials in Netlify

**- What is the expected behavior?**

Being able to store encrypted credentials to external services like an API key.

**Comment by verythorough** [comment]
@DirtyF I've been thinking about the same thing! Basically a command to sync the build environment variables stored in Netlify's UI with a local .env file.

**Comment by DirtyF** [comment]
Truth is this feature was asked by @pixelastic because you need to pass Algolia's credentials 🔑 to build you search index and push it to your account ⬆️ .

**Comment by bcomnes** [comment]
I definitely agree with you, this is critical.   This is a platform level change we are current interested in and tracking.  Since this doesn't appear to be specifically related to the CLI, I'm going to close this issue.  If I've left something CLI specific unaddressed, please let me know and we can re-open.  I'm going to do some research to see how far off this is and if its not coming soon, we can perhaps explore a cli related solution.

**Comment by pixelastic** [comment]
> Just to confirm, this request is to specifically support better ENV secrete management in our builds bots, similar to what appveyor and travis have, correct?

Yes, this is what I was looking for

**Comment by marcinczenko** [comment]
Hmm...am I wrong or `Build environment variables` are not available for manual deployments...?
