### ISSUE TITLE
Fix randomly failing tests

### ISSUE THREAD

**Issue by ehmicky** [netlify/cli#1368]
Some tests are randomly failing.

From discussing with @erezrokah, this seems to be because some of our tests are sending requests to our production API. Rate limiting or other factors might make those tests randomly fail.

This problem was making 95% of GitHub actions workflows fail, which was a major problem when trying to merge PRs. Due to this, I have added `test.skip()` to the following [test file](https://github.com/netlify/cli/blob/master/tests/command.dev.trace.test.js) which was failing more often than others. This helped this problem a little, but did not completely solve it.

**Comment by erezrokah** [comment]
We have some tests hitting the Netlify AP which we increased the limit for. Other tests (the ones you skipped) are hitting the GitHub API without an auth token and are bound to much lower limits.

A detailed explanation:
For traffic mesh we are using a [dependency](https://github.com/netlify/gh-release-fetch) that downloads the latest version from GitHub (also used for live client tunnel). That dependency uses GitHub API without a token so the rate limits are very strict and done per IP. Usually that’s not an issue but if we run many CI jobs in parallel we might hit that. It’s hasn’t been an issue so far since for those two tests we should hit the API about 4 times I think. But in case we have a lot of CI jobs it can become a serious issue. GitHub API limits are reset once per hour, so when you do hit them it's hard to recover.

We could fix it by allowing to pass an auth token to the dependency to get much better rate limits or publish the traffic mesh agent as an npm package. The latter would prevent the `auto update` feature we have at the moment as each agent version will be locked in the CLI version.

**Comment by erezrokah** [comment]
Fixed via https://github.com/netlify/cli/pull/1388
