### ISSUE TITLE
command line flags from v1.0 are not present in v2.0

### ISSUE THREAD

**Issue by kishor-dabi** [netlify/cli#144]
In the old version of the CLI, you could pass site ID and token via command line flags.  In the new version you can instead (today, already!) use environment variables as described here: 

https://github.com/netlify/cli/blob/master/docs/deploy.md

Here's an example of the flags that are missing from 2.0:

+ netlify deploy -p dist -s $DEVELOPMENT_SITE_ID -t $NETLIFY_TOKEN
 ›   Error: Unexpected arguments: dist, -s, 
 ›   bbd92d82-ba17-4b57-b87d-2152e5b05045, -t, 
 ›   $NETLIFY_TOKEN
 ›   See more help with --help

The version of cli is 2.0

**Comment by fool** [comment]
Hi there,

Sounds like you're using the old-style syntax from v1.0.  In version 2, at present you'll need to use environment variables alone:

https://github.com/netlify/cli/blob/master/docs/deploy.md

rather than command line flags.  

Still, we'll leave this issue open to track as a feature request and I'll edit the title and report to reflect that.

**Comment by bcomnes** [comment]
@kishor-dabi I am adding flags back to the deploy command for `site_id` and `auth_token`.  Keep an eye out for a release soon.  I'll close this when that is out.

**Comment by kishor-dabi** [comment]
Thanks for the reply and update for this

**Comment by bcomnes** [comment]
I released a beta that should address this issue: see https://github.com/netlify/cli/pull/147#issuecomment-429497857

Expect a full release monday.

**Comment by bcomnes** [comment]
🎉[`netlify-cli@2.1.0`](https://github.com/netlify/cli/releases/tag/v2.1.0)🎉
