### ISSUE TITLE
Regression: cannot provide human-readable site name

### ISSUE THREAD

**Issue by mojodna** [netlify/cli#157]
With the previous version of the CLI, I was deploying to a specific site using

```bash
netlify deploy -p dist/ -s planet-stac
```

With the new version of the CLI, I now need to use

```bash
netlify deploy --prod --dir dist/ --site 95a54956-1c9b-4548-87bc-<redacted>
```

Is it possible to use the human-readable name when deploying sites using the new CLI?

**Comment by bcomnes** [comment]
Possibly.  Is this for a more readable CI script?  When used interactively, the ideas is once you are logged in, and your local folder is linked to a site, `netlify deploy` is useful without any flags.

**Comment by bcomnes** [comment]
I looked into this some more, and this should be easier than I expected.  We can add this back.

**Comment by mojodna** [comment]
It's for a repo that's deployed to multiple sites to visualize different datasets: https://github.com/radiantearth/stac-browser/blob/master/package.json#L12-L14

It's not linked to a single site as a result, and having readable names makes it easier for new people to understand/use.

Thanks!!

**Comment by MichalBryxi** [comment]
Also note that it's currently confusing in the documentation, because in various places (and possibly blog posts) it [reads](https://github.com/netlify/cli/blob/master/docs/deploy.md):

> site (option) - A site ID to deploy to

But on the netlify web: `https://app.netlify.com/sites/{myapp}/settings/general` the closest to *site id* I can find is *site name*, which worked till now. Second best guess is *API ID*, which is actually correct.

And when you provide wrong ID netlify-cli just spits out:
```
 netlify deploy
 ›   Error: Not Found
```

Without any possibility to figure out what's wrong. At least I haven't found `--verbose` or `--debug` flag for it.
