### ISSUE TITLE
`netlify init` throws a 403 "GitHub error" on `Create & configure a new site`

### ISSUE THREAD

**Issue by lindsaylevine** [netlify/cli#1611]
**Describe the bug**

<img width="735" alt="Screen Shot 2020-12-01 at 1 13 41 AM" src="https://user-images.githubusercontent.com/57350178/100705967-21bb1b80-3376-11eb-865c-bce378108e2e.png">

`netlify logout` and `netlify login` does not make a difference. `rm -rf .netlify` also does not make a difference.

The site actually does get created though, despite the 403s.

cc @erezrokah 

**To Reproduce**

1. Clone https://github.com/lindsaylevine/blender-resources
2. Navigate to the cloned repository
3. Run `netlify init` and auth through Github
4. Choose create & configure a new site
5. See output with 403

**Configuration**

[build]
  command   = "npm run build"
  functions = "out_functions"
  publish   = "out_publish"

<img width="435" alt="Screen Shot 2020-12-01 at 1 41 02 AM" src="https://user-images.githubusercontent.com/57350178/100706039-4911e880-3376-11eb-9f8d-b42abefd8f68.png">

**Expected behavior**

No 403 which to be honest made me think the site creation actually failed for awhile (😅)

** Additional **

Also happened with another project:

<img width="1200" alt="Screen Shot 2020-11-28 at 8 21 54 PM" src="https://user-images.githubusercontent.com/57350178/100706483-19afab80-3377-11eb-96b8-f97767a97f5c.png">

**Comment by erezrokah** [comment]
Thanks for opening this @lindsaylevine, and sorry for the late reply.
I can't be 100% sure this is a CLI issue since we're missing some error handling and logs in that part of the code.
I've created a PR to address that https://github.com/netlify/cli/pull/1619.

From the second screenshot it looks like that deleting `~/.netlify` (the one in the home directory and not the repo) doesn't help with this.

When authentication with Netlify the CLI receives the token from the UI app, so it looks like the CLI is getting a token with wrong permissions.

For the second screenshot, does the error happens after approving the authentication in the opened browser window or before?

**Comment by lindsaylevine** [comment]
no worries at all!!!!!!!

for the second screenshot, the error happens *after* authing in the browser

**Comment by lindsaylevine** [comment]
*and* _after_ the site is created, which successfully gets created, weirdly

**Comment by erezrokah** [comment]
The CLI first creates the site, then tries to add a deploy key on GitHub - which I believe this is the part that's failing.
We should probably verify the GitHub's token permissions first, but I'll need to figure was the cause of the error first.

**Comment by serhalp** [comment]
Marking this as stale as it is is several years old.
