### ISSUE TITLE
`deploy --dir dist --prod` not triggering Netlify plugins

### ISSUE THREAD

**Issue by arinthros** [netlify/cli#1671]
**Describe the bug**

I have the Algolia Crawler plugin set up in Netlify, but it's not being triggered when using a manual deploy from the CLI.
See https://github.com/algolia/algoliasearch-netlify/issues/157

It appears that `netlify deploy --dir dist --prod` is not correctly triggering plugins that should be running on deploys.

**To Reproduce**

1. In any Netlify project with Netlify plugins (or specifically Algolia Crawler), run `netlify deploy --dir <dist-folder> --prod`
2. Wait for a successful run
3. Check the site's deploy details
4. See that no plugins were triggered

**Configuration**

We run a Gitlab CI pipeline to build the dist files, then use netlify-cli to deploy them.

gitlab-ci.yml
```yml
- npm run build
- npm i -g netlify-cli
- netlify deploy --dir dist --prod
```

netlify.toml
```toml
[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['production']
  renderJavaScript = true
```

- Please enter the following command in a terminal and copy/paste its output:
*We run a fresh install every time of netlify-cli*

**Expected behavior**

When using `netlify deploy --dir dist --prod`, I expect Netlify plugins to trigger and do their thing.

**CLI Output**

Not applicable.

**Additional context**

See https://github.com/algolia/algoliasearch-netlify/issues/157

**Comment by verythorough** [comment]
As their name suggests, Build Plugins require a build. Since manual deploys don't run a build, we don't have a build container to run plugins. If you're deploying from CLI, you can run `netlify deploy --build`, which will run a build command (and hence start a build container) before deploying. 

If your site is already "built" at the time you run `netlify deploy --build`, you could modify your build command so that it doesn't re-build your site. I think (but haven't tested) that you could set this in your `netlify.toml` file roughly like so:

```
[context.production]
command = ""
publish = "dist"
```

And then the CLI command would be `netlify deploy --build --prod`. This would skip running any build command (or more accurately, would run an empty build command), but would not skip dependency installation. We're working on adding an option for build to skip dependency installation in the future, though.

**Comment by erezrokah** [comment]
Adding to @verythorough's suggestion, I think you should be able to simplify your `gitlab-ci.yml` by using:
```yml
- npm i -g netlify-cli
- netlify deploy --build --dir dist --prod
```

**Comment by erezrokah** [comment]
Closing the issue. @arinthros please comment if still relevant
