### ISSUE TITLE
Netlify CLI keeps adding overzealous and incorrect rule to .gitignore

### ISSUE THREAD

**Issue by SleeplessByte** [netlify/cli#2029]
**Describe the bug**

In my `.gitignore` I have the following intentional line:

```gitignore
/.netlify
```

Linking a new site / running CLI in several ways will **incorrectly add**:

```gitignore
# Local Netlify folder
.netlify
```

In order to make my monorepos work again I have to add:

```gitignore
!sites/**/.netlify
```

**To Reproduce**

1. Create a new git repo
2. Add `.gitignore` with `/.netlify`
3. Run `netlify deploy`
4. It has added the line to `.gitignore`

**Configuration**

```bash
npx envinfo --system --binaries --npmPackages netlify-cli --npmGlobalPackages netlify-cli


  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
    Memory: 5.80 GB / 31.91 GB
  Binaries:
    Node: 12.18.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\Documents\GitHub\delftsolutions\@introcloud\app\node_modules\.bin\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    netlify-cli: ^3.10.12 => 3.10.12

```

**Expected behavior**

It does not add `.netlify` to `.gitignore`.

**Comment by SleeplessByte** [comment]
The biggest issue with this is that it will silently fail on changes / new files. You won't notice until your build starts failing somewhere else (for example, because there is no `state.json` available. It's counter-intuitive and frankly, I hate that it's doing something to my `.gitignore` _without telling me_.

**Comment by erezrokah** [comment]
Hi @SleeplessByte, linking https://github.com/netlify/cli/issues/506 for context.
I agree this is not an ideal experience.

To clarify - you only want to ignore `.netlify` at the root level? Any reason you want to commit `state.json`? 
Please note that the `.netlify` folder can also contain temporary files generated during `netlify build` and other information that should not be committed to the repo.

**Comment by SleeplessByte** [comment]
You got it.

We have our own build and then only use netlify deploy, so those other files never get generated.

state.json holds the siteId and is a far better tool to configure ci builds for a folder then trying to do it via environment variables.

**Comment by SleeplessByte** [comment]
The linked issue has very similar concerns (and remains unresolved).

I see the following options:

- only ignore the files that contain sensitive information,
- unignore state.json
- ask a user

The notion that you need to protect users who might not understand and therefore do this automatically is understandable, but in my opinion not the right way. By not notifying such a user, and make it a conscious decision, a user is never taught that the folder may contain sensitive data, and what that sensitive data is.

It's also pretty elitist to decide for everyone how their projects should be structured but I think that was made clear in the previous issue from 2 years ago :)

**Comment by erezrokah** [comment]
I think we can solve this by looking for a `.netlify` substring in the patterns here https://github.com/netlify/cli/blob/14b1b7751fa259c78fc12e4f1207ca765ac7b483/src/utils/gitignore.js#L95 instead of trying to find a full match.

That would allow us to support both use cases WDYT?

Regardless we should add a log message when we add `.netlify` to `.gitignore`.

In addition we should re-visit the "sensitive data" reasoning  since users can unignore `.netlify` anyways or copy that directory with the folder to another location unaware of having that folder copied around.

Finally we'll need to make sure that if users do commit `state.json` (out of choice or mistake) we handle possible failures resulting from it (e.g. the site was deleted so the information in `state.json` is no longer valid).

How does that sound?

**Comment by SleeplessByte** [comment]
All go that sounds like it will solve my issues, the original issue, and potential future issues, so it got my seal of approval.
