### ISSUE TITLE
Support base configuration in `init` command

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2302]
**Is your feature request related to a problem? Please describe.**

The `netlify init` command only prompts for publish dir, build command and functions directory.
We should also add support for the base directory.

**Describe the solution you'd like**

Prompting the user for a base directory, default is undefined

**Describe alternatives you've considered**

Letting the user configure it manually via the UI, after the first build fails.

**Additional context**

N/A

**Can you submit a pull request?**

Yes

- [x] https://github.com/netlify/cli/issues/2380

**Comment by erezrokah** [comment]
Related to https://github.com/netlify/cli/issues/433

**Comment by verythorough** [comment]
Note that there's some trickiness here with the `netlify.toml` file:
- If the `init` flow is pulling settings from the toml file, it should look for the file in the `base` directory, so the base directory prompt should probably be first, before the build command & publish directory. (It will also be first in the UI.)
- The end of the `init` flow asks whether the user would like to save the settings to a `netlify.toml` file. If the `base` directory is set, the file should be saved there, and it should _not_ include the `base` setting. (The `base` setting _could_ be set in a root toml file, but this won't work if there's more than one sub-project in the repo.)

It occurs to me that the first point is also relevant for framework heuristics, which should also be run in the `base` directory.

**Comment by erezrokah** [comment]
Great points @verythorough!

We need to consider that the user can run `netlify init` from within the repository root or from within the base directory itself.

Looks like running from within the base directory will work as we search the config file from that directory and up:
https://github.com/netlify/build/blob/6ed8ab9f55690981d8f6c1216ebb1b5bc0efd8c4/packages/config/src/path.js#L16
cc @ehmicky can you confirm?

If the user runs `netlify init` from the repository root, we'll need to pass the `base` to `netlify/config` so the correct file will be resolved.
That is a bit tricky as at the moment the first thing we do in the CLI is to resolve the configuration, so we would need to call `netlify/config` a second time after getting the `base` directory from the user.

**Comment by ehmicky** [comment]
Yes, we are searching the config file from that directory and up :+1:

**Comment by verythorough** [comment]
> We need to consider that the user can run `netlify init` from within the repository root or from within the base directory itself.

Oh, I didn't think about that!

So I did some experimenting with that workflow, using a basic monorepo testing repo I had:
https://github.com/verythorough/monorepo-test

1. Ran `ntl init` in `/projects/project1` (no config file in that folder), while there was no config file in the root:
	- Creates a `.gitignore` file at the repo root.
	- Stores the `.netlify` folder with `state.json` in `/projects/project1`.
	- Publish directory is relative to repo root, since there's no base.
	- Prompts to save a config file, then stores it in the repo root.
	- No base directory set in the UI.
	- The deploy on Netlify runs from the root, publishing the wrong folder because no base is set.
	- Running `ntl dev` from the subfolder detects no build command; runs a static server from the subdirectory.
	- Running `ntl build` from the subfolder pulls settings from UI and runs the build in the subfolder (as if the base was set).
	- Running `ntl deploy` from the subfolder deploys from the subfolder to the linked site. If a publish directory is set in the UI, it deploys that directory, with path relative to the project subdirectory.
2. Ran `ntl init` in `/projects/project1` (no config file in that folder), with a config file in the repo root:
	- Same as above, except:
		- Creates a `.gitignore` file in the subdirectory
		- Does not prompt to save a config file.
		- The deploy on Netlify runs with the root-level config file, which doesn't match the project settings. The resulting deploy is wrong.
3. Ran `ntl init` in `/projects/project2`, which has a config file inside:
	- Creates a `.gitignore` file in the subdirectory
	- Settings prompts use subdirectory config file values for defaults
	- Does not prompt to save a config file.
	- No base directory set in the UI.
	- The deploy on Netlify runs with the root-level config file, which doesn't match the project settings. The resulting deploy is wrong.
	- Running `dev`, `build`, and `deploy` works the same as above.
4. Ran `ntl init` in the repo root, with a config file that sets `/projects/project2` as `base`:
	- Creates a `.gitignore` file at the repo root.
	- Stores the `.netlify` folder with `state.json` in the repo root.
	- Settings prompts use config file values from `/projects/project2` for defaults.
	- No prompt to save a config file.
	- No base directory set in the UI.
	- The deploy on Netlify pulls the `base` setting from the root config file, then pulls the command and publish directory from the base directory config file.
	- Running `dev`, `build`, and `deploy` works the same as above.

**Some of my big takeaways from this:**
- Tests 1-3 all fail to deploy correctly in continuous deployment.
- Test 4 basically worked as expected and documented, but of course it doesn't work for more than one site per repo. 
- This also made me realize that the flow I described in my previous comments would also work for only one site per repo, because (I think) you can only link one site per directory. 

Thinking through that a bit, I sketched out a flow that I think could cover all of the use cases:
![When running init, first ask the user if it's being run in the folder where the site is built. If not, tell them to cd to the folder and re-run. If so, run as usual if root, run with base set if not.](https://user-images.githubusercontent.com/6111186/117726842-06adcc80-b19c-11eb-904b-168325b88207.png)
(Click the image for a readable version. 😆)

It also lends itself fairly well to iteration. For example:
- Start by changing `init` so that it sets the base to cwd if it's run from a repo subdirectory. (Basically skip the medium teal parts from the flow and just implement the light grey parts.) Docs can instruct users to run from a subdirectory when needed.
- Add the prompts in the medium teal sections of the flow. User still needs to `cd` and re-run `init`.
- Potentially build the whole flow into a single run of `init`, asking the user which directory to use, `cd`'ing to it (while informing the user), and then running the rest from there.

We wouldn't _have_ to break it up like that, but we could, and each step would still be useful. What do you think?

**Comment by verythorough** [comment]
> I think there's one additional use case - users can have a monorepo but not use the `base` setting, for example by having either a root `package.json` with a build command that builds a specific site, or by `cd` into a sub directory as a part of the build command (e.g. `command = "cd packages/project1 && npm run build"`).
> 
> We should encourage users to use the `base` command as it makes things more clear.

Great point!

**Comment by erezrokah** [comment]
@verythorough I've updated the title of the issue to reflect it being a top level issue.
I've opened https://github.com/netlify/cli/issues/2380 to describe the first iteration and also renamed the title for https://github.com/netlify/cli/issues/433 to reflect the discussion there.

**Comment by erezrokah** [comment]
https://github.com/netlify/cli/issues/2380 is released in https://github.com/netlify/cli/releases/tag/v3.31.0

**Comment by erquhart** [comment]
Updated title to prioritize human readability for tracking across GitHub

**Comment by erezrokah** [comment]
Closing if favor of https://github.com/netlify/cli/issues/3224
