### ISSUE TITLE
fix(docs-contributing): clarify our deploy tests create a live site

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#2541]
We instruct users to run `npm test` as a part of the [development process](https://github.com/netlify/cli/blob/main/CONTRIBUTING.md#development-process).

The [deploy tests](https://github.com/netlify/cli/blob/main/tests/command.deploy.test.js) are creating a live site using the user authentication token, on the first [account they find](https://github.com/netlify/cli/blob/1ead8569414d4e2d3ebd4f903c5da4dcfbc219c8/tests/utils/create-live-test-site.js#L32).

We should document it, as it can be confusing for new contributors.

**Comment by tinfoil-knight** [comment]
To clarify, does running the integration tests consume any Netlify credits?

**Comment by erezrokah** [comment]
Hi @tinfoil-knight, do you mean build minuets?

If so the answer it that they don't cost build minuets. The only tests that create a live site are the [deploy command tests](https://github.com/netlify/cli/blob/c883b6e76aca955b3c4d04475ec96c61993827c9/tests/command.deploy.test.js#L42).
Those deploy directly and don't use our build system.
Also, you can disable those by setting the the `IS_FORK` environment variable to `true`.

**Comment by tinfoil-knight** [comment]
@erezrokah Netlify charges for building the sites on basis of how much time a build runs.

I was confused if the integration tests consumes those. Thanks for clarifying.

**Comment by tinfoil-knight** [comment]
Current:
**NOTE**: we run some integration tests against an active Netlify account. For these tests to pass you'll need to provide a Netlify auth token (using the NETLIFY_AUTH_TOKEN environment variable) or login via `./bin/run login` before running the tests.

---

Proposed (Building on your comment):

Running `npm test` will require an active Netlify account because we run some integration tests on a live site.

You can either provide a [Netlify Auth Token](https://docs.netlify.com/cli/get-started/#obtain-a-token-in-the-netlify-ui) (through the `NETLIFY_AUTH_TOKEN` environment variable) or login via `./bin/run login`.

Also, these integration tests deploy a site directly and don't use the Netlify build system so running these won't result in any charges towards your Netlify account.

P.S. We don't recommend doing this but if you want to disable the tests which deploy a site through your Netlify account, you can do so by setting the `IS_FORK` environment variable to true.

**Comment by erezrokah** [comment]
Thanks @tinfoil-knight how about we also improve the following:
1. Rename `IS_FORK` to `NETLIFY_TEST_DISABLE_LIVE`
2. When running the tests - detect if we're running in CI:
    - If running in CI and no authentication information was provided - fail the tests
    - If running in CI and authentication information was provided - run the tests
    - If not running in CI and no authentication information was provided - skip the tests and print a warning
    - If not running in CI and authentication information was provided - run the tests and print a log message explaining they don't use build minuets and also how to disable them.
    
Then we'll have the information as part of the dev workflow.
  
WDYT?

**Comment by tinfoil-knight** [comment]
Sounds great. Some things to clarify before a PR:

- `IS_FORK` env variable is available through `process.env` and will be `false` in the CI
- `CI` env variable would be `true` while tests are running in CI
- `listAccounts()` in `create-live-test-site` can be used to check if any authenticated accounts are available.

**Comment by erezrokah** [comment]
> Would the standard `CI` env variable would be `true` while tests are running in CI?

We run our CI in GitHub actions and they set it to `true`. Regardless [we use `ci-info` for that](https://github.com/netlify/cli/blob/9434040b3247ddebf6cadfeee7e42c8726dfa237/package.json#L103).

**Comment by tinfoil-knight** [comment]
Alright. Can you assign me the issue?

**Comment by tinfoil-knight** [comment]
>    * If not running in CI and no authentication information was provided - skip the tests and print a warning

I read ava's docs and browsed through their issues, there isn't a way to skip tests. (We could disable them like we do for the `IS_FORK` variable but this might confuse people more when their tests pass locally and fail on the CI. Since the tests run for about 20mins, people might miss the warning.)
