### ISSUE TITLE
How to surface headers parsing errors in the CLI

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#3154]
**Is your feature request related to a problem? Please describe.**

In Production we ignore headers parsing errors, however for the CLI we might want to error/warn about those so users can fix them.

**Describe the solution you'd like**

Not sure yet, I would say error to make it visible, but open to discussion (warning as a first step might be safer)

**Describe alternatives you've considered**

Ignore the errors like we do in Production

**Additional context**

Related to https://github.com/netlify/netlify-headers-parser/pull/10

**Can you submit a pull request?**

Yes

**Comment by ehmicky** [comment]
Thanks for opening this @erezrokah!
I think this discussion applies to redirects as well, and fits within our "Local development" big bet.

In production, we actually do surface almost all parsing errors for both headers and redirects in the Deploy summary, under the collapsible menu. From that perspective, surfacing those errors makes sense and would be helpful to users.

When it comes to warning vs errors:
  1. Warnings would keep the behavior closer to production, which just ignores invalid headers/redirects and keeps parsing others
  2. Errors would bring a stricter validation to local development, which might be helpful since all users probably intend to fix syntax errors in headers/redirects and might just not be aware of them nor reading the build logs. 

I would personally lean towards `2.`, but I can see a case being made for `1.` as well.
What are your thoughts on this?

**Comment by ehmicky** [comment]
Since `netlify build` and `netlify deploy --build` can be used in a CI settings, I would personally lean towards this behavior for invalid headers/redirects:
  - With `netlify dev`, fail (new behavior)
  - In production and with `netlify build` and `netlify deploy --build`, print warning messages (current behavior)

If anyone has concerns over implementing this, please let me know.

**Comment by erezrokah** [comment]
> Since `netlify build` and `netlify deploy --build` can be used in a CI settings

I think we could investigate how the CLI operates in CI environments (e.g. detects it and have different defaults), but that's out of scope for this issue.

**Comment by ehmicky** [comment]
From discussing with @erezrokah, we decided that headers/redirects errors in `netlify dev` should print an error message, but not stop the command.

**Comment by ehmicky** [comment]
Fixed by #3225.
