### ISSUE TITLE
Add `onPreDev` build plugin hook

### ISSUE THREAD

**Issue by ascorbic** [netlify/cli#3184]
**Is your feature request related to a problem? Please describe.**

Build plugins are now able to mutate the config at build time. However these changes are not persisted when running `ntl dev`. 

**Describe the solution you'd like**

Add a new build plugin hook, e.g. `onPreDev`, which is called when running `ntl dev` and before spawning the site's develop command. This could be used to update the configuration, inject env vars etc.

**Describe alternatives you've considered**

- Currently we write out a `_redirects` file if we need redirects to be available during dev, rather than using config mutation. This is fragile, prevents the use of redirects from the TOML file, and means that plugins must require users to run `build` bedore they can run `dev`.
- Persist config changes made during `build`. However this wouldn't allow us to use different redirects for develop, and could give unexpected results if the user didn't run `build` beforehand. This also requires `build` to be run before `dev`

**Comment by erezrokah** [comment]
For Essential Next.js, some work has been done to support a [`watch` mode](https://github.com/netlify/next-on-netlify/pull/162).

The idea was for the CLI to detect the plugin, and run it in watch mode per https://github.com/netlify/next-on-netlify#preview-locally.

The `onPreDev` also works.

**Comment by ehmicky** [comment]
I think this might tie to a bigger problem: builds (production or local) and `netlify dev` are currently completely separate. For example, `netlify dev` does not call `@netlify/build` nor Build plugins at all.

Extending Build plugins to support `netlify dev` might not be straightforward because Build plugins currently assume they are spawned within `@netlify/build`. The process and environment in which they are currently spawned is very different from `netlify dev`. To take one of many examples, Build plugins are wrapped in code which orchestrate them, handle their errors, pass utilities, etc. which we don't have an equivalent for in `netlify dev` at the moment.

In my opinion, we should consider trying to bridge that gap and integrate `@netlify/build` and `netlify dev` more together. But until we do this, it seems to me we might need to explore other solutions that Build plugins to solve the underlying problem of this issue.

**Comment by ascorbic** [comment]
This was implemented!
