### ISSUE TITLE
[Low Priority] Suppress core-js logs

### ISSUE THREAD

**Issue by sdras** [netlify/cli#325]
**Bug**
This is low priority, but the `core-js` logs upon install are off-topic for our own tool. What I'm specifically concerned with is that these logs are potentially confusing for newer developers trying out our CLI.

Here's what I've discovered so far:
- There are several env variable conditions to be met in core-js to display the warning, but haven't found a way to create an env variable that wasn't in a child process, even in a `preinstall` hook
- The log should be suppressed if it's in `devDependencies`- this is a problem because if a transitive dep declares it as a regular dependency, we'll still see the logs. And yeah, if you check, (run `npm ls core-js`) this isn't actually our dependency, looks like our testing frameworks are using it as a direct dependency, and need to. 

I'm not sure there's much to be done here as there's a bit of debate already surfaced about it: https://github.com/zloirock/core-js/issues/548

**- What is the current behavior?**
When you install our CLI, you get bright cyan core-js logs

**- If the current behavior is a bug, please provide the steps to reproduce.**
`npm i -g netlify-cli`

**- What is the expected behavior?**
Just our logs, specific to this tool

**- Please mention your node.js, and operating system version.**
v12.1.0 MacOS Mojave

Really just documenting this because otherwise I'll forget what the story was here.

**Comment by jschatz1** [comment]
Looking at the dependency tree with `npm ls`: [dependency_tree.txt](https://github.com/netlify/cli/files/3306781/deps.txt). 

`core-js` is a transitive dep. It's required by: 

- `auto-changelog` -> a dev dependency so it should not install on `npm install netlify-cli` but will on `npm install`
- `ava` -> a dev dependency same as above.

I'm not totally sure why it's installing on `npm install -g netlify-cli`. I'm clearly missing something.

**Comment by DavidWells** [comment]
Its not possible to remove logs from NPM dep install hooks (unless something has changed since npm v5 release). I tried this a while ago for a similar issue at serverless.

There are a couple of work arounds.

1. Publish CLI as binary (via something like [pkg](https://github.com/zeit/pkg), or brew). This will require removing `opn` and any other dep that won't port into single binary
2. Release CLI via headless desktop app like now. This is how zeit automatically keeps the users CLI up to date, has custom install flow, & many other goodies an electron app provides (custom protocols etc)
3. Fork the dependancies & remove the logs (and maintain the forks)
4. Change the dependancies
5. Contact the author of the dependency and ask them to remove the message

None of the above are great options, except maybe #2 where we streamline install flow & add additional UX benefits from a headless app.

**Comment by jschatz1** [comment]
One other way to solve this which others have used is to use [`pkg`](https://www.npmjs.com/package/pkg)

**Comment by jschatz1** [comment]
I'm going to give `pkg` a try. This would solve a lot of problems for us. I created an issue here: https://github.com/netlify/cli/issues/337

**Comment by raeesbhatti** [comment]
A temporary patch would be to change the install instructions on the website to include `-q` (quiet) flag. e.g. `npm install -gq`. This will suppress the "donate" instructions output from the `postinstall` script of `core-js`.

**Comment by DavidWells** [comment]
I think @imorente solved this issue with https://github.com/netlify/cli/pull/338

It makes the dev deps not ship with the module. If i recall correctly?

**Comment by imorente** [comment]
> It makes the dev deps not ship with the module. If i recall correctly?

That's correct!

**Comment by DavidWells** [comment]
Fixed thanks @imorente !
