### ISSUE TITLE
feature: `env:list` should hide environment variables values by default, and prompt to show them

### ISSUE THREAD

**Issue by erezrokah** [netlify/cli#3579]
**Is your feature request related to a problem? Please describe.**

The default view of `env:list` shows the value of environment variables.
This can unintentionally expose secrets like API tokens, database credentials, etc. 

**Describe the solution you'd like**

Hide values by default (in the default view, keep showing them in `--json`).
Add confirmation prompt to show them.

**Describe alternatives you've considered**

Keeping the values visible by default

**Additional context**

Related to https://github.com/netlify/cli/issues/3262

**Comment by rodneycoyer** [comment]
Hi! I was reading through the thread and would like to contribute to this feature.

To confirm:
1. Only display key variable names from `env:list` table.
2. add a prompt asking the user if they want to see the full `key: value` table.

I was wondering if, instead of a prompt, we only update the docs referring devs to the `--json`  flag if they want to see the full `key: value` table. RN the docs don't mention anything about it.

**Comment by erezrokah** [comment]
> RN the docs don't mention anything about it.

That's a good point. We missed this in the initial implementation. We'll need to add a `json` flag to the `env:list` command to show it in the docs, similar to https://github.com/netlify/cli/blob/51e7b69dd8065b18081c564aeb6d1e225d83380a/src/commands/sites/list.js#L78

Our docs are autogenerated from those, so that's the reason it's missing from the docs. It still works because of the following code:
https://github.com/netlify/cli/blob/51e7b69dd8065b18081c564aeb6d1e225d83380a/src/utils/command.js?_pjax=%23repo-content-pjax-container#L147

I would still keep the flow of a prompt as the `json` flag is intended for machine usage (e.g. parsing the result in CI).
