### ISSUE TITLE
External redirects don't work without 200 status

### ISSUE THREAD

**Issue by Hrishikesh-K** [netlify/cli#3770]
**Describe the bug:**

A [user reported on the forums](https://answers.netlify.com/t/redirects-netlify-dev-works-only-with-200-status-code/48049/) that they were not able to get the external redirects to work with Netlify CLI. The redirect syntax is valid.

Upon further investigation, it looks like CLI is adding the redirect correctly, but the `location` header is incorrect. For example, with the following `_redirects` file:

```
/foo https://www.netlify.com/ 301!
```

I see this:

![image](https://user-images.githubusercontent.com/11403551/144749264-edd42252-c690-40ab-938a-b94c01a9e1c8.png)

It's basically redirecting it back to the home page.

**To reproduce:**

1. Create ` _redirects` file as mentioned above and an `index.html` in a working directory. It can be simple as:

```html
<!doctype html>
<html>
  <head>
    <title>Foo</title>
  </head>
  <body>
    <p>Hi!</p>
  </body>
</html>
```
2. Run `netlify dev`.
3. Try visiting `dev-url/foo`.

**Configuration:**

```bash
  System:
    OS: macOS 12.0.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 796.11 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    npm: 6.14.14 - ~/.nvm/versions/node/v14.17.5/bin/npm
  npmPackages:
    netlify-cli: ^8.0.15 => 8.0.15 
```

**Expected behaviour:**

It should redirect to the required URL.

**CLI Output**

If applicable, add the CLI output to help explain your problem.

**Additional context**

This seems to work fine with the `200!` configuration.

**Comment by tinfoil-knight** [comment]
@lukasholzer I was trying to debug this issue.

This is the place where redirects are handled:

https://github.com/netlify/cli/blob/47bf5eb7df9dfaf1ba9571cc9fc1b403935f0474/src/utils/proxy.js#L216-L227

The `isRedirect` function matches all redirects with http status code `301`. Therefore, instead of reaching the `isExternal` branch, the redirect for the external url is handled in the `isRedirect` branch itself which is causing the issue.

https://github.com/netlify/cli/blob/47bf5eb7df9dfaf1ba9571cc9fc1b403935f0474/src/utils/proxy.js#L79-L81

Switching the order of these blocks should resolve the issue. Can I make a PR for this?

**Comment by lukasholzer** [comment]
@tinfoil-knight do you want to continue and take over on this issue?

**Comment by tinfoil-knight** [comment]
> @tinfoil-knight do you want to continue and take over on this issue?

Yes. Thank you.
