### ISSUE TITLE
Infer default value for Identity headers in `functions:invoke` command

### ISSUE THREAD

**Issue by eduardoboucas** [netlify/cli#3954]
**Is your feature request related to a problem? Please describe.**

When using the `functions:invoke` command, I'm always asked for input about whether or not to have emulated Identity headers:

```
% ntl functions:invoke test
◈ "port" flag was not specified. Attempting to connect to localhost:8888 by default
? Invoke with emulated Netlify Identity authentication headers? (pass --identity/--no-identity to override) (Y/n)
```

It would be great if we could use a default option, requiring no additional input from the user, and offer overrides via the existing flags.

**Describe the solution you'd like**

The default should be no Identity unless the function is one of the Identity triggers (see https://docs.netlify.com/functions/trigger-on-events/#available-triggers).

**Comment by karagulamos** [comment]
We can safely eliminate the check that invokes the prompt and reduce the if-else to this single line:
   
    `const isAuthenticated = options.identity || false`

This works since passing an **--identity** flag yields a **true** value while a `--no-identity` (or when omitted) yields a **false**.  Also, I doubt we need to do anything more for identity trigger functions as the existing code seems to correctly handle that use case.

I did a PR for the fix here https://github.com/netlify/cli/pull/3971 for your review/approval.
