### ISSUE TITLE
implement pretty url simulation

### ISSUE THREAD

**Issue by sw-yx** [netlify/cli#416]
**- Do you want to request a *feature* or report a *bug*?**
bug

**- What is the current behavior?**
https://community.netlify.com/t/netlify-dev-and-pretty-urls/1761

**Comment by RaeesBhatti** [comment]
This has been supported since some time now. If user requests `/something` and `/something.html` is available or `/something/index.html` is available, we will serve that for static websites.
Not possible with framework based app servers because they implement their own routing logic and don't return 404 on not found URL's.
