### ISSUE TITLE
Proxy Redirects Fail when running "netlify dev"

### ISSUE THREAD

**Issue by paulrostorp** [netlify/cli#425]
**I am trying to proxy the "/graph" path to my local graphql server running on localhost:4000, but  I am getting an error.** 
1) I start my react app with "netlify dev" command called from package.json script.
2) My netlify.toml is looks like this:
````
[build]
   functions = "built-lambdas"
[[redirects]]
    from = "/graph"
    to = "http://localhost:4000/"
    status = 200
````
3) The dev server for the app works without a problem, I can edit the code and save and server refreshes with updated code.
But when I try to interact with the /graph path (localhost:8888/graph), either through mutations in my app or directly accessing the address through the browser, I get the following error: 
````
◈ Proxying to  http://localhost:4000/
[HPM] Proxy created: /  ->  http://localhost
[HPM] Error occurred while trying to proxy request / from localhost:8888 to http://localhost (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
````

**What I have tried:**
Changing the paths and addresses (to /graph/, /graph/*, http://localhost:4000/, http://[1::]:4000, http://127.0.0.1:4000/,... etc  but also changed "to" address to the web url of my production graphql api)
Am I doing anything wrong or is this a bug ? Any guidance would be appreciated.
Thanks

-------
Mac os 10.14.4
node.js 10.14.1
netlify-cli@2.11.20

**Comment by raeesbhatti** [comment]
Hey @paulrostorp thanks for reporting. It seems like you're not using the correct port for the functions server. The default port is 34567. You can configure it using `--functionsPort` with `netlify dev` or using the [`functionsPort` declaration](https://github.com/netlify/cli/blob/master/docs/netlify-dev.md#netlifytoml-dev-block) in the `dev` section of your netlify.toml.
There was another issue that might have been causing a similar issue even when using the correct port, which has been fixed in the latest release. Please update using `npm i -g netlify-cli@latest` and let us know.
