### ISSUE TITLE
[DX] Read .env files in the `functions` directory

### ISSUE THREAD

**Issue by kentcdodds** [netlify/cli#474]
I configure env variables in the netlify UI, but locally I use `.gitignore`d `.env` files and https://www.npmjs.com/package/dotenv-cli to run netlify-lambda with the right env variables.

It'd be cool if netlify-dev-plugin could solve this problem somehow :)

**Comment by uptownhr** [comment]
Not sure if this is the right thread for this but I also ran into env variable issues when trying out netlify dev. I would actually wish that .toml file environmental variables be used in netlify dev and made available not just to the site but also to the functions. This would provide a single place to handle environmental variables for both dev and production

**Comment by BrunoQuaresma** [comment]
Is there any workaround to get `.env` files working on `netlify dev`?

**Comment by bsgreenb** [comment]
Shouldn't Netlify Dev environment just be its own deploy context?

Also am personally finding that Netlify kind of clashes with my dotenv setup, so would definitely appreciate a dotenv friendly approach.

**Comment by dferber90** [comment]
> I'm finding that I cannot override any `process.env` variables when using `dotenv` in combination with `netlify dev`.
> 
> And I can confirm that `dotenv` is called (via the log):
> 
> ```
> Request from ::ffff:127.0.0.1: GET /.netlify/functions/auth/twitter
> isProduction false
> Loading dotenv config...
> ```

@owenconti  This happens because `netlify dev` will set the environment variables before `dotenv` gets a chance to run. `dotenv` doesn't overwrite existing environment variables (see https://www.npmjs.com/package/dotenv#what-happens-to-environment-variables-that-were-already-set), so the value defined in Netlify wins.

---

@BrunoQuaresma Here's a snippet which enables overwriting env vars defined in Netlify with env vars from `.env`. This only works for Netlify functions though, not for your client-side code. Note that this snippet would have to be pasted at the top of every function you want to use.

```js
const dotenv = require("dotenv")
const envConfig = dotenv.config();
// "parsed" will be undefined when no .env file was present,
// in which case we need to skip the call to Object.entries
if (envConfig.parsed) {
  Object.entries(envConfig.parsed).forEach(([key, value]) => {
    process.env[key] = value;
  });
}
```

<details>
<summary>Or as a short version</summary>

```js
const envConfig = require("dotenv").config();
Object.entries(envConfig.parsed || {}).forEach(
  ([key, value]) => (process.env[key] = value)
);
```

</details>

---

@sw-yx 

> but if anyone feels strongly that we should auto-read a .env file in the root directory, i'm open to the idea but want buyin from everyone

I too would appreciate out-of-the-box support for `.env` in `netlify dev`. I want to use most env vars defined in Netlify, while being able to overwrite specific ones using a `.env` file. My specific use-case is that I have a token for a payment provider, where I'd use a the sandbox token in development and the real one in production.

> also have to consider conventions like https://github.com/kentcdodds/kentcdodds.com which has `.env.production` and `.env.development`

The concept of `.env.production` and `.env.development` doesn't really make sense to me in this case. To me `.env.production` are the env vars stored in Netlify, while `.env.development` is what I'd store in `.env`.

<details>
<summary>Some ideas/ramblings</summary>

What might be nice to have (from my limited understanding) is a way to provide env var overwrites for different [deploy contexts](https://docs.netlify.com/site-deploys/overview/#deploy-contexts) through the Netlify UI. That would enable using different API keys for production and preview branches easily. Additionally `netlify dev` could have its own section there, where we could define overwrites of env vars for `netlify dev` as well. Then devs wouldn't need to pass `.env` files to new team members. I've always been wondering how other Netlify users are solving this. I'm aware of overwrites in `netlify.toml`, but I wouldn't want to commit those and therefore `netlify.toml` isn't an option for me here.

</details>

**Comment by ksaturnius** [comment]
From a security perspective, the reading of .env files would be a really nice addition. In particular, for our use case, we're using Storyblok as a headless cms. In order to interact with their content management api, there is a per-user api key required. It would be ideal for each dev to use their own key during development and have our infra/ops account owner on Storyblok generate the key that is used in production. I'm thinking there would be two parts to this:

1. Provide an optional "lock" mechanism in the Netlify admin that prevents the Netlify-cli from automatically injecting it's environment variables into local dev environments. This would entirely prevent exposure of any environment variables added via the Netlify admin outside of the Netlify pipeline.
2. Allow loading of `.env` files locally, which would automatically overwrite the values injected by the Netlify cli (in case the environment variables haven't already been "locked" as per above).

**Comment by DavidWells** [comment]
Env support is coming soon with https://github.com/netlify/cli/pull/616 and new https://github.com/netlify/build pipeline

You will be able to reference environment variables in config files

```yml
key: ${env:MY_ENV_VAR}
```

**Comment by trevorblades** [comment]
An alternative technique that I've been using recently is setting my `_DEV` and `_PROD` environment variables in the UI, and then switching on `process.env.NETLIFY_DEV` in my lambda function, which is `true` when I'm using `netlify dev`.

```
setClientSecret(
  process.env.NETLIFY_DEV
    ? process.env.CLIENT_SECRET_DEV
    : process.env.CLIENT_SECRET_PROD
);
```

I don't know how well-documented this `NETLIFY_DEV` env variable is, but it's a life saver!
