### ISSUE TITLE
"ReferenceError: Request is not defined" when installing on Node 16

### ISSUE THREAD

**Issue by DEPT-ch** [netlify/cli#5961]
### Describe the bug

Installing on Node 16 leads to this error:

```
error /Users/sklaus/.config/yarn/global/node_modules/netlify-cli: Command failed.
Exit code: 1
Command: node ./scripts/postinstall.mjs
Arguments: 
Directory: /Users/sklaus/.config/yarn/global/node_modules/netlify-cli
Output:
file:///Users/sklaus/.config/yarn/global/node_modules/@netlify/serverless-functions-api/dist/index.js:1523
var NetlifyRequest = class extends Request {
                     ^

ReferenceError: Request is not defined
    at file:///Users/sklaus/.config/yarn/global/node_modules/@netlify/serverless-functions-api/dist/index.js:1523:22
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
```

### Steps to reproduce

1. Install latest Node 16 (in my case `nvm install 16`)
2. Install latest netlify-cli globally (in my case `yarn global add netlify-cli`)

### Environment

  System:
    OS: macOS 13.4.1
    CPU: (8) arm64 Apple M1
    Memory: 64.09 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
    pnpm: 7.27.0 - ~/Library/pnpm/pnpm

**Comment by pixeljae** [comment]
Getting the same issue running node 16.18.  Tested with npm and it works fine however.

**Comment by eduardoboucas** [comment]
This was a problem in one of our transitive dependencies. We never updated CLI with it, but sadly Yarn doesn't respect the lock file so it still pulled in that version. npm does respect it, so that's why it wasn't an issue there.

In any case, we've already fixed the problem in the transitive dependency, so this shouldn't be a problem anymore. Could you please try again?

Sorry for the inconvenience.
