### ISSUE TITLE
CI failing with "We've detected multiple sites inside your repository"

### ISSUE THREAD

**Issue by scottlovegrove** [netlify/cli#5977]
### Describe the bug

I have a CI deployment that has been working fine until it started using v16 of the CLI.

The command I have within my deployment script looks like this
```
npx netlify-cli deploy --prod --dir=./webclient/dist
```

But when that command now runs, and pulls down v16, the deployment fails with 

```
We've detected multiple sites inside your repository
? Select the site you want to work with (Use arrow keys or type to search)
❯ @shiftsync/apiclient  apiclient  --filter @shiftsync/apiclient 
  @shiftsync/core  core  --filter @shiftsync/core 
Error: Process completed with exit code 130.
```

I specified the version to be 15 and deployment ran through ok, letting it pull 16 again results in the same error, every time.

My repo has the following structure:
![image](https://github.com/netlify/cli/assets/25244878/95a84297-165e-4f03-a172-8c04a63c2bb9)

The command is run from the root of the repo, passing in the webclient/dist folder once the build has finished earlier in the CI process.

### Steps to reproduce

I'm unsure how to repro this outside of a CI environment. If I try and run the same command locally, after building the web app, the cli client ends up publishing a blank site.

### Environment

  System:
    OS: Linux 5.15 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (2) x64 Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz
    Memory: 22.16 GB / 31.35 GB
    Container: Yes
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 18.16.0 - ~/.local/state/fnm_multishells/22934_1693641170757/bin/node
    npm: 9.5.1 - ~/.local/state/fnm_multishells/22934_1693641170757/bin/npm
  npmGlobalPackages:
    netlify-cli: 15.8.1

**Comment by chinanderm** [comment]
Noticing this too on v16. Downgraded and pinned to v15.11.0 to get our CI/CD pipeline for deployments working again.

**Comment by lukasholzer** [comment]
Hey, @scottlovegrove, thanks for reaching out.

First of all, multiple things are happening here; let me maybe explain to you:

We've released a new major (breaking) version that added better monorepo support. We rely on [Semantic Versioning](https://semver.org/), where a new major version indicates that this contains breaking changes and might break existing workflows.

here are the docs for it: https://docs.netlify.com/cli/get-started/#work-with-monorepos
and here is the changelog post: https://www.netlify.com/blog/better-monorepos-on-netlify/

Sadly, we could not introduce this new feature without breaking existing workflows.
The significant change is that if you run from the root of a monorepo, we need to know which part you want to work on. A command is always tied to serve one app or deploy one app so we need to know which app is that -> therefore you can see the prompt. This is mainly required for new ways to store and read up configuration files (see docs). 

You can bypass this prompt by changing to this directory before or using the `--filter` flag in CI/CD environments.

@South-Paw the reason on why the CLI deploy cannot omit the `--filter` flag when an explicit dir is specified is that a dir does not match a site. We are still missing which configuration file to pick up or about the `siteId`, which is stored in the `.netlify/state.json`. As a monorepo can have 1 to n sites stored in it we cannot have this information stored on the repository root.

A good example where the publish directory differs from the package location is Nx (a popular monorepository build system). There the publish directory would be `dist/apps/app-1` and the configuration files would be stored at: `apps/app-1/{netlify.toml,|netlify/state.json}`

```
/
├─ apps/
│  ├─ app-1/
│  │  ├─ .netlify/state.json
│  │  ├─ package.json
│  │  ├─ netlify.toml
│  │  ├─ ...app-1-source-files
│  ├─ app-2/
│  │  ├─ .netlify/state.json
│  │  ├─ package.json
│  │  ├─ netlify.toml
│  │  ├─ ...app-2-source-files
│
├─ other-packages/
│  ├─ component-library/
│  │  ├─ package.json
│  │  ├─ ...component-library-source-files
│
├─ package.json
```

@scottlovegrove I hope this helps troubleshoot this issue for you. If there is still an issue or something does not work I'm more than happy to help you get it sorted out if you provide more information (framework, folder tree, etc.) or maybe a simple reproducible example.

**Comment by South-Paw** [comment]
@lukasholzer 👋

Our monorepo doesn't actually use `.netlify/state.json` files in any projects, we just pass the env variable `NETLIFY_SITE_ID` with the deploy command in GitHub action workflows.

We don't use NX, just npm workspaces and dist folders end up inside the app directories - not the root. I've also raised #6000 as somewhere along the line the CLI now manages to deploy our entire project to the Netlify site rather than the specified dir... which was fantastic to discover.

It just seems like Netlify CLI is making a lot of assumptions about project toolchain and setups that are then being built into the CLI commands (e.g. filter and now the deploy cwds)

**Comment by lukasholzer** [comment]
Sorry for the frustration @South-Paw. 

Regarding the `.netlify` folder, this is something internal netlify is creating and relying on for storing internal state and build outputs like bundled functions etc. 

Now if you have multiple applications, we cannot store them in the root as this would collide. 
If you don't need those things, then it's one point, but others might do. I was not thinking that you use Nx just wanted to point out that it is not that easy to omit the `--filter` flag when a dir is provided as it might fit your use case, but we have to consider way more ways to develop in a monorepo.

If you could maybe tell us some of the hiccups and things that frustrated you on debugging this, this would be so helpful so we can try to make it more obvious and better in the future.

There will be always bugs, so anything we can do to make troubleshooting/issue creation easier is something I would love to do!

**Comment by jgeringer** [comment]
Hi @lukasholzer ,

We are experiencing a similar issue after upgrading netlify-cli from 15.11.0 to 16.4.2. We too are now getting the "We've detected multiple sites inside your repository" message when running `netlify dev`. Note that we do use npm workspaces and have two package.json files: One at the root of the repo, and one in a subfolder of root. The problem is that when running `netlify dev`, the "We've detected multiple sites inside your repository" list prompt only displays one site (the one in the subfolder) and not the one on the root level. Do you know if there is a way to have it pickup the root level?

Note: We've tried netlify dev --filter [root package.json name property value] but it still prompts us to only select the one in the subfolder.

Thanks!

**Comment by lukasholzer** [comment]
@jgeringer I would love to understand your use case more on having a workspace, but it seems that the root is a package as well? 

So while implementing the workspace feature, we've tried to stick to the implementation logic of [pnpm workspaces](https://pnpm.io/workspaces), [yarn workspaces](https://classic.yarnpkg.com/lang/en/docs/workspaces/) and [npm workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces) where the goal is to have everything in sub packages distributed to the workspace.

There is indeed a way how to bypass the `--filter` flag and fall back to the old behavior by providing the `--cwd .` flag (when running from the root). 

In this case, you tell the CLI that you know where the current working directory is, and we don't have to perform heuristics about where we can detect it in a workspace.

Nevertheless, I would love to understand your use case or maybe you can share some details about your workspace structure!

**Comment by jgeringer** [comment]
Hi [@lukasholzer](https://github.com/lukasholzer) , thanks for the quick reply!
Yes, that's correct, in our case, the root is a package as well. Great to know about the `--cwd` flag, haven't seen that one [in the cli docs](https://cli.netlify.com/). Is that page, and [the getting started page](https://docs.netlify.com/cli/get-started/), the most up to date place to find info about the Netlify CLI?

In our case, we would like to be able to run a script in one of the packages in a sub directory first, and then when that is done, run a script in the root package. If they were broken out into sibling directories, they wouldn't be able to communicate in that order. Sounds like we would have to re-work our directory structure later on or use the `--cwd` flag. Thank you!

**Comment by jzempel** [comment]
@lukasholzer rather than relying on an undocumented `--cwd` flag, would it be better if `netlify-cli` were updated to use something like [is-interactive](https://www.npmjs.com/package/is-interactive) to determine whether or not to prompt the user for monorepo sites?

**Comment by ForbesLindesay** [comment]
This was incredibly frustrating. I just want to upload a directory as a netlify website. Everything's already built and in the correct folder.

I tried:

- `netlify deploy --dir=packages/website/out` causes the `We've detected multiple sites inside your repository` error (https://github.com/ForbesLindesay/atdatabases/actions/runs/7505463095/job/20434753256)
- `cd packages/website && netlify deploy --dir=out` causes the `Site not found. Please rerun "netlify link"` error (https://github.com/ForbesLindesay/atdatabases/actions/runs/7505707413/job/20435547129)
- `netlify deploy --filter @databases/website --dir=packages/website/out` also causes the `Site not found. Please rerun "netlify link"` error (https://github.com/ForbesLindesay/atdatabases/actions/runs/7505811436/job/20435883558)
- `netlify deploy --cwd . --dir=packages/website/out` is back to the `We've detected multiple sites inside your repository` error (https://github.com/ForbesLindesay/atdatabases/actions/runs/7506008454/job/20436482067)

The magic incantation that finally worked (https://github.com/ForbesLindesay/atdatabases/actions/runs/7506096220/job/20436748850) is:

```sh
netlify deploy --cwd . --filter @databases/website --dir=packages/website/out
```

Could you maybe add a simple command for uploading/deploying a directory? If I wanted netlify to magically figure out how to install dependencies & build the site for me, I'd be using netlify's CI service. The whole reason I'm using the CLI is because I want to just upload an already built directory to an existing site.

**Comment by lukasholzer** [comment]
@ForbesLindesay for that there is the `--cwd` command this should not need the `--filter`.

So, in your case, `netlify deploy --cwd packages/website/out` should be enough.

I understand your request, but the CLI must work for complex scenarios where we detect a framework inside a monorepo, as well as a lot of customers facing this challenge. Using the CLI just to upload a directory is not really common.

**Comment by lukasholzer** [comment]
Instead of using the "non-public" `--cwd` flag you could just set the cwd of your github actions task or CI runnter to the cwd of the monorepo like `apps/my-app` this should work as well

**Comment by smrubin** [comment]
Is there documentation around the recommended command for deploying a monorepo app with the netlify cli? Particularly, which options should be present in addition to `--filter`?
