### ISSUE TITLE
Netlify dev command not starting dev environment with Angular

### ISSUE THREAD

**Issue by hanshank** [netlify/cli#652]
**- Do you want to request a _feature_ or report a _bug_?**
Yes

**- What is the current behavior?**
I am running an Angular: 8.2.14 application on a Macbook Pro 13’.

My problem:
I am trying to run netlify dev inside my angular project. After entering the command in th cli I just get:

◈ Netlify Dev ◈
◈ Starting Netlify Dev with undefined

The server doesn’t start.

In my netlify.toml file I have:

[dev]
command = “npm start” # I have also tried ng serve
port = 3000 # Port that the dev server will be listening on
functionsPort = 34567 # port for functions server
publish = “dist/my-app-name”

What I have tried

I tried using yarn instead of npm, still having the same problem.
I ran “npx react-create-app app-name” followed by “netlify dev” which worked fine!
I tried reinstalling the netlify-cli -> Didn’t help
My Question
What could possibly be wrong? Is this a bug?

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new angular project with angular cli command "ng new <app-name>"
2. Create a netlify.toml file with something like this:
[dev]
  command = "npm start" # Command to start your dev server
  port = 4200 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder

3. Enter "netlify dev" through the CLI in the project folder.

4. the command fires and it looks but the only output I get is:
◈ Netlify Dev ◈
◈ Starting Netlify Dev with undefined

5. The command exits and no server starts.

**- What is the expected behavior?**
I want to type "netlify dev" and have my local environment spin up.

**- Local Environment Information**
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 68.0.1
    Safari: 13.0.4

**Comment by mtopping** [comment]
I ran into a similar issue but after "Starting Netlify Dev with undefined" I was getting an error that node was undefined. This was because I am using nvm and the process is run in a non-interactive shell.

The easiest path forward for me was:

**netlify-dev.sh**
```
#!/bin/bash
export NVM_DIR="/Users/mt/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

nvm use 10
npm run start
```
**run `chmod +x netlify-dev.sh`**

**netlify.toml**
```
...
[dev]
  command = "./netlify-dev.sh"
  targetPort = 4200 # Port of target app server
  publish = "."
...
```

The "undefined" is just an artifact of netlify-cli not having a detector for angular and ended up being a red herring for me.

**Comment by hanshank** [comment]
Awesome! Thank you @mtopping

**Comment by rolodato** [comment]
I've run into a similar issue on a Hugo-based website, not using Angular or Angular CLI in my case. I think the root cause is Netlify CLI not using the calling shell's environment variables, including `PATH`. Calling `env` from a build script invoked by Netlify CLI returns this:

```
PWD=/Users/rolodato/my-project-directory
FORCE_COLOR=true
SHLVL=1
_=/usr/bin/env
```

@mtopping's workaround works for me, but I prefer to use it this way:

* Avoid hardcoding your home directory by using `~`
* Specify the Node version in `.nvmrc` and call `nvm use` with no parameters. This way you only need to specify the desired Node version in one place: https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript
* Don't load bash completion as it's not needed

```sh
#!/usr/bin/env bash

NVM_DIR=~/.nvm
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

nvm use
npm run start
```
