### ISSUE TITLE
Ensure manual deploys work with Gitlab

### ISSUE THREAD

**Issue by bcomnes** [netlify/cli#78]
It's been reported that manual deploys aren't working with gitlab.  Also, url links to the repo on manual `init`'s are linking to get remote urls, instead of http urls.

**Comment by sam3d** [comment]
To clarify, as I think I'm experiencing the same problem, GitLab deploys don't work if the `origin` URL is `https://`, right?

I've been able to get them to work if they're `ssh`, but I'm assuming this is because the implicit conversion to `https://` URL's is only supported on GitHub using the [parse-github-url](https://github.com/jonschlinkert/parse-github-url) package?

**Comment by erezrokah** [comment]
I believe this was resolved in https://github.com/netlify/cli/pull/1619 by letting users confirm the parsed URL.
Please comment if that's not the case
