### ISSUE TITLE
netlify dev works but functions fail with "error while proxying request: socket hang up"

### ISSUE THREAD

**Issue by dimavolo** [netlify/cli#846]
**- Do you want to request a _feature_ or report a _bug_?**
Bug

**- What is the current behavior?**
I reviewed the existing issues that are similar to this, but found no solutions.

`netlify dev` successfully starts a server, serving a `vue cli` app at `http://localhost:8888`, but all calls to functions result in `error while proxying request: socket hang up`

**- If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an app with Vue Cli
2. Create a function in /functions
3. Create a netlify.toml file:
4. In a Vue view, perform a `fetch` request at any variation of `/functions/foo`
5. Netlify reports: `error while proxying request: socket hang up`

    [build]
    Command = "yarn serve"
    Functions = "functions"
    Publish = "dist"

**- What is the expected behavior?**

Netlify builds the dev server for Vue (which it does successfully now) and also the functions server, so that functions in `/functions` get called.

**- Local Environment Information**

────────────────────┐
 Environment Info   │
────────────────────┘

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
  Binaries:
    Node: 13.8.0 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 74.0.1
    Safari: 13.0.5
  npmGlobalPackages:
    netlify-cli: 2.47.0

netlify-cli/2.47.0 darwin-x64 node-v13.8.0

**Comment by RaeesBhatti** [comment]
`socket hang up` only happens when the client backs off before a request is completed. e.g. refreshing the browser window before the request was complete.
Also note that this is only a warning, only affects the specific http request and will not crash the server.
It could be that Vue `fetch` request is being cancelled before completion. Can you try the same request using `curl` and report that has the same problem!
