### ISSUE TITLE
Bug: deploy command regression

### ISSUE THREAD

**Issue by DavidWells** [netlify/cli#859]
The `netlify deploy` command used to deploy one of my sites has stopped working in `netlify-cli@2.48.0` 

The command `netlify deploy` fails with a "Base directory does not exist" error.

```
> netlify deploy -p --dir public

Base directory does not exist: /Users/davidwells/David/analytics-project/analytics/site/main/site
```

Was something changed recently with the `netlify deploy` command?

This is the site in question: https://github.com/DavidWells/analytics/tree/master/site/main and the previously working deploy script is here:  https://github.com/DavidWells/analytics/blob/master/site/main/package.json#L14

**Comment by DavidWells** [comment]
It looks like this is an error coming from netlify/config https://github.com/netlify/build/blob/b6006915061ecd890a7d4f8b857cddc22e778f1a/packages/config/src/files.js#L65 cc @ehmicky

**Comment by DavidWells** [comment]
Reverting to `netlify-cli@2.40.0` fixes this error

**Comment by ehmicky** [comment]
Just to confirm, I think the error message should be `
Base directory does not exist: /Users/davidwells/David/analytics-project/analytics/site/main/public`, not `
Base directory does not exist: /Users/davidwells/David/analytics-project/analytics/site/main/site` if you passed `--dir public`, please confirm if that's not the case.

It looks like the issue is that the `public` directory does not exist and you're trying to deploy it. Did you run `npm run build` first?

**Comment by DavidWells** [comment]
The build folder is there locally. This is a regression in how the CLI works. Possibly related to how this site uses yarn workspaces? IDK

`netlify deploy -p --dir public` should deploy my site, instead it results in "Base directory does not exist: /xyz/site" Error with latest versions of CLI

**Comment by ehmicky** [comment]
I am having issues reproducing this problem. When I make sure `npm run build` has been run first, `npm run deploy` seems to work fine for me with the latest version of `netlify-cli`. @RaeesBhatti Do you manage to reproduce this issue?

**Comment by DavidWells** [comment]
Related https://github.com/netlify/cli/issues/862

**Comment by RaeesBhatti** [comment]
@DavidWells Can you try the following branch! see if you can still reproduce this issue there: https://github.com/netlify/cli/pull/843

**Comment by timchambers** [comment]
I'm also hitting this now. Did not occur in 2.41.0, does occur in 2.42.0 and later. I'm also using yarn workspaces with this repository, in case that helps, since @DavidWells mentiojned he is as well.

**Comment by zacaytion** [comment]
I'm having this issue too on version `2.47.0`. I'm using yarn workspaces with two netlify projects and a wrapper bash script to handle the deploy logic. 
I don't have the issue when I'm calling the cli directly from the shell, but when executing it via a bash script it appears to be interpreting the path wrong. 
When calling the script from the `/web` directory in my workspace and passing the directory to deploy as `/build` the CLI is assuming I want to deploy the build located at `/web/web/build` rather than `/web/build`.

Reverting to version `2.40.0` resolved the issue

**Comment by DavidWells** [comment]
Any updates on this one? 

I am having to uninstall the latest CLI and install the old version to successfully deploy my site. 😢

**Comment by DavidWells** [comment]
Hardcoding `netlify-cli@2.41.0` into my project for right now and using the local dependency is how I'm "solving this" currently.

```
  "scripts": {
    "deploy": "./node_modules/.bin/netlify deploy -p --dir public",
  }
```

^ for anyone else experiencing this issue

**Comment by RaeesBhatti** [comment]
Not yet. I haven't been able to reproduce it locally. It seems like a problem specific with yarn workspaces setup. @DavidWells If you can write down step-by-step instructions to reproduce this, that will be greatly appreciated!

**Comment by DavidWells** [comment]
1. Clone down https://github.com/DavidWells/analytics
2. Cd into https://github.com/DavidWells/analytics/tree/master/site
3. Run yarn to install deps
4. `npm install netlify-cli -g`
5. Build the site `npm run build`
6. Attempt to deploy site `npm run deploy`
7. This fails unless on `netlify-cli@2.41.0` or lower

**Comment by DavidWells** [comment]
Using  

```
yarn --version
1.17.3
node --version
v12.7.0
```

**Comment by RaeesBhatti** [comment]
Not sure what's going on but I was able to deploy the site successfully following your instructions exactly!
<img width="697" alt="Screen Shot 2020-05-21 at 8 36 52 PM" src="https://user-images.githubusercontent.com/10067728/82628876-ec519c00-9ba2-11ea-80e9-8a52d0234c48.png">

```
% yarn --version
1.17.3
% node --version
v12.16.3
```

**Comment by cadbox1** [comment]
I had a similar issue with `netlify dev` `>2.41.0` and fixed it by adding the following to my `netlify.toml`:

```
base = "./"
```
reference: https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file

**Comment by DavidWells** [comment]
I thought this was a mono repo issue but it appears its happening on other sites as well 😢

Here is another example. https://github.com/DavidWells/awesome-stoicism/blob/master/site/package.json#L11

With any CLI version above `netlify-cli@2.41.0` the `deploy` script fails with the same message: `Base directory does not exist: /Users/davidwells/David/repos/stoic-quotes/site/site`. `site/site` is incorrect.

To "fix" this I've had to instead the Netlify CLI as a dev dependency at version `2.41.0`. Using `netlify-cli@2.41.0` the deploy script succeeds as expected.

**Comment by verythorough** [comment]
Based on the clues from @cadbox1's comment, I suspect the repro attempts might not be working because the sites they're creating differ from @DavidWells's original failing sites in one of two ways:

- The failing sites might have a base directory set in the UI.
- The failing sites might have been created before October 2019, when the introduction of monorepo support changed how base and publish directories are handled.

Neither of those things would be true of the new sites being created for repro testing.

**Comment by erezrokah** [comment]
I was able to reproduce this issue based on https://github.com/netlify/cli/issues/859#issuecomment-642387765 and https://github.com/netlify/cli/issues/859#issuecomment-642394874

Looks like this reproduces if you set a base directory in the UI:
![image](https://user-images.githubusercontent.com/26760571/85569101-ebe17080-b63a-11ea-8673-1e3b34fd09fa.png)

Netlify build tries to resolve the configuration before the `--dir` flag is even read.
Resolving the config happens here:
https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/utils/command.js#L76

While evaluating the `--dir` flag happens here:
https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/commands/deploy.js#L105

The CLI reports a repository root of `<repo>/site` since it looks for `['.netlify', 'netlify.toml', '.git']` when searching for the root:
https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/utils/command.js#L28
https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/utils/find-root/index.js#L14

and `build` will resolve the build directory based on the site settings to `<repo>/site/site`

I can solve this by removing `repositoryRoot: projectRoot` here:
https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/utils/command.js#L79
and let `build` find the root of the project (it has logic to do so and only relies on searching for `.git`).

Or we can let the CLI pass additional information to `build` on how to resolve the `base` directory.

@ehmicky, @RaeesBhatti thoughts?

**Comment by ehmicky** [comment]
`@netlify/config` needs to know the `repositoryRoot` for several reasons inside the configuration resolution logic.

There are some mismatches between how `@netlify/config` and `@netlify/cli` compute the repository root.

The default value for `repositoryRoot` in `@netlify/config`: 
  - Looks for the nearest `.git`, from `cwd` up
  - Or defaults to `cwd`. 
  - `@netlify/cli` has a `--cwd` CLI flag to override `cwd`, which is passed to `@netlify/config`.

The `projectRoot` variable in `@netlify/cli`: 
  - Looks up for the nearest `.git`, `.netlify` or `netlify.toml`, from `cwd` up (using the same `cwd` as above)
  - Or defaults to `cwd`. 
  - If `projectRoot` is the home directory, [it uses `cwd` instead](https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/utils/find-root/index.js#L18). This is probably because the [global configuration](https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/utils/global-config.js) is set in `~/.netlify/config.json`.
  - The `_projectRoot` variable overrides it, but is always `undefined`. It probably is meant for unit testing, but does not appear used at the moment.
 
I suggest:
  - Adding `.netlify` and `netlify.toml` to the logic in `@netlify/config`. This should not be a problem in production since the buildbot passes an explicit `repositoryRoot` flag.
  - Adding the home directory behavior as well to `@netlify/config`.
  - Do not pass any `repositoryRoot` CLI flag from `@netlify/cli` to `@netlify/config`.
  - Return the resolved `repositoryRoot` from `@netlify/config`, and use this in `@netlify/cli` as the `projectRoot`.
  - Remove the logic to resolve `projectRoot` from `@netlify/cli`, since `@netlify/config` would now handle it.

When it comes to the `--dir` CLI flag, which basically overrides `build.publish`, I think this should be passed as input to `@netlify/config` since it is responsible for resolving the configuration, which includes `build.publish`. For example, `@netlify/cli` is [currently defaulting](https://github.com/netlify/cli/blob/2ddcff30c64c4ab8329214d59fb261f1213dc494/src/commands/deploy.js#L105) that flag to `build.publish` then to the UI Publish directory (`build_settings.dir`), but `@netlify/cli` is already doing this. 

The logic of all this is quite intricate. For example, the current logic in `@netlify/cli` for `build.publish` is not taking into account contexts. Consolidating this logic inside `@netlify/config` would help prevent problems.

This goes for other potential flags. For example, I see the `netlify deploy` has a `--alias` CLI flag. If this corresponds to the notion of build contexts (context or branch), then this should be passed to `@netlify/config` `context` option. Otherwise the resolved configuration will not be applied context-specific configuration during `netlify deploy`.

**Comment by erezrokah** [comment]
@ehmicky that's is a great analysis and there is some work to be done on consolidation.
We would first need to map out different use cases and make sure they are covered by tests.

To be more focused on this issue with the `base` directory - I would expect that when running from the CLI we would always ignore the UI/config settings for `base` and resolve the build directory using the current working directory.

More specifically running `netlify deploy --prod --dir out` should work when invoked from `repo/site` and `netlify deploy --prod --dir site/out` should work from invoked from `repo` (in the latter the CLI should not ask to link to a site if `site/.netlify` exists).

That should work for multiple sites under the same repo as well  (e.g. `netlify deploy --prod --dir site1/out`, `netlify deploy --prod --dir site2/out`).

**Comment by ehmicky** [comment]
We just discussed with @erezrokah and went with the following solution, which should solve this bug:
  - In `@netlify/config`, if `cwd` is a subdirectory of `repositoryRoot`, tries to find if any directory (that is `>= cwd && < repositoryRoot` in the tree structure) that has a `.netlify` or `netlify.toml`. If one exists, this is used as build.base, regardless of what base is set in `netlify.toml` or UI build settings. 
  - Since `build.base` is used to compute `buildDir`, `@netlify/cli` can now use the `buildDir` returned by `@netlify/config` as its `projectDir`/`projectRoot`/`site.root` which is used to find `.netlify/state.json` and resolve `publish`, `functions`, `.env`, `_headers`, `_redirects`, etc.
  - Do not pass any `repositoryRoot` flag from `@netlify/cli` to `@netlify/config`. Instead, let `@netlify/config` compute it by looking up `.git` from `cwd`

For the CLI flags (`--dir`, `--functions`, `--site`, `--alias`), I still think those should be fixed to re-use the logic from `@netlify/config`. They currently do not account for many use cases (properties case-insensitivity, contexts, etc.). We can create separate issues/bugs for each of those, separately from this issue though.

**Comment by erquhart** [comment]
Thanks to both of you for digging into this!

**Comment by ehmicky** [comment]
First part (`@netlify/config` `base` behavior) done in https://github.com/netlify/build/pull/1581

**Comment by ehmicky** [comment]
The `buildDir` returned by `@netlify/config` cannot be used to find `.netlify/state.json`. This is because there is a cycle:
  - `.netlify/state.json` is located at `buildDir`
  - `buildDir` is computed from `base`
  - `base` is partially computed from the UI build setting "Base directory"
  - That build setting is retrieved using the `getSite` endpoint 
  - The `getSite` endpoint needs the `siteId`
  - The `siteId` is red from `.netlify/state.json`

One way to solve this is to make an exception for `.netlify/state.json` and use CLI-specific logic to retrieve it instead of the `buildDir` returned by `@netlify/config`. `.netlify/state.json` only contains `siteId` at the moment, and is highly CLI-specific anyway. Separating those concerns actually helps out reduce the size of the changes needed for this problem. I have implemented this solution, and it works :+1:

**Comment by ehmicky** [comment]
https://github.com/netlify/build/pull/1581 is merged and released to npm.

@erezrokah Would it be possible to test https://github.com/netlify/cli/pull/953 and see if the problem that you managed to reproduce is now fixed?

**Comment by DavidWells** [comment]
Ran into another example of this. 

- With latest CLI, build fails with `  Base directory does not exist: /Users/xyz/site/frontend/site` error
- After reverting to `netlify-cli@2.40.0` the deployment proceeds.

These are the logs:

```
  site git:(master) ✗ npm run deploy

  > abc-site@0.1.0 deploy /Users/xyz/site
  > netlify deploy --prod --dir out

  Base directory does not exist: /Users/xyz/site/frontend/site
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! abc-site@0.1.0 deploy: `netlify deploy --prod --dir out`
  npm ERR! Exit status 1
  npm ERR!
  npm ERR! Failed at the abc-site@0.1.0 deploy script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  npm ERR! A complete log of this run can be found in:
  npm ERR!     /Users/davidwells/.npm/_logs/2020-06-27T02_18_38_177Z-debug.log
  ➜  site git:(master) ✗ npm i netlify-cli@2.40.0 --save-dev

  > netlify-cli@2.40.0 postinstall /Users/xyz/site/node_modules/netlify-cli
  > node ./scripts/postinstall.js


  Success! Netlify CLI has been installed!

  Your device is now configured to use Netlify CLI to deploy and manage your Netlify sites.

  Next steps:

    netlify init     Connect or create a Netlify site from current directory
    netlify deploy   Deploy the latest changes to your Netlify site

  For more information on the CLI run netlify help
  Or visit the docs at https://cli.netlify.com

  + netlify-cli@2.40.0
  added 34 packages from 17 contributors, removed 49 packages, updated 20 packages, moved 11 packages and audited 2033 packages in 26.379s
  found 1 moderate severity vulnerability
    run `npm audit fix` to fix them, or `npm audit` for details
  ➜  site git:(master) ✗ npm run deploy

  > abc-site@0.1.0 deploy /Users/xyz/site
  > netlify deploy --prod --dir out

  Deploy path:        /Users/xyz/site/out
  Functions path:     /Users/xyz/site/functions
  Configuration path: /Users/xyz/site/netlify.toml
  Deploying to live site URL...
  ✔ Finished hashing 39 files and 1 functions
  ✔ CDN requesting 16 files and 1 functions
  ✔ Finished uploading 17 assets
  ✔ Deploy is live!

  Logs:              https://app.netlify.com/sites/xyz/deploys/123123
  Unique Deploy URL: https://12312312323--xyz-site.netlify.app
  Live URL:          https://xyz-site.netlify.app
```

**Comment by ehmicky** [comment]
Hi everyone,

This bug should be fixed with `netlify-cli@2.56.0`.

If the problem persists, please add the `--debug` CLI flag and share the full output of the CLI command (including the command itself). Please also show the output of the following command:

```
npx envinfo --system --binaries --npmPackages @netlify/build,@netlify/config,@netlify/git-utils,@netlify/cache-utils,@netlify/functions-utils,@netlify/run-utils,netlify-cli --npmGlobalPackages @netlify/build,netlify-cli
```

If the bug is fixed by upgrading to `netlify-cli@2.56.0`, please let us know as well, so we can close this issue. Thanks!

**Comment by cadbox1** [comment]
`netlify dev` is now working for me on `netlify-cli@2.57.0`. 

No need to add a temporary `base` property to my `netlify.toml` anymore.

Thanks! 👍

**Comment by iamchathu** [comment]
What are the changes needs to do to mitigate this issue? I'm also having `monorepo` setup and for new `netlify-cli` version build fails it get publish directory from root and `netlify.toml` from the internal project.

```
Deploy path:        /builds/abc/pqr/project/build
Configuration path: /builds/abc/pqr/project/packages/internal-package/netlify.toml

```

And my `netlify.toml` is like

```toml
[build]
  base = "."
  publish = "./build/"
  command = "yarn build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

**Comment by ehmicky** [comment]
Hi @iamchathu,

Could you please print your logs when running the Netlify CLI, with the environment variable `NETLIFY_BUILD_DEBUG` set to `true`? 
Also the output of `netlify --version` and `./node_modules/.bin/netlify-config --version`. 
Thanks!

**Comment by ehmicky** [comment]
Hi @squirly,

Thanks a lot for this information.
I have setup a PR at https://github.com/netlify/build/pull/1770 which should solve this problem.

**Comment by ehmicky** [comment]
`@netlify/config@2.1.2` has been published, which should solve your problem.
To get the new version, you will need to regenerate your `package-lock.json` or `yarn.lock`. To confirm you're using the right version, please run `netlify-config --version` and make sure the output is at least `2.1.2`.

@squirly and @iamchathu, could you please use the new version of `@netlify/config` as described above, try again, and confirm this is solving the issue? Thanks!

**Comment by squirly** [comment]
@ehmicky Rad! This fix worked for me. Thanks for the quick response!

**Comment by ehmicky** [comment]
Great! Closing this issue.
The fix will be available in the next release of `netlify-cli`. In the meantime, regenerating your lock file and ensuring `@netlify/config` is `>= 2.1.2` should do the trick. Thanks!
