### ISSUE TITLE
`build` does not respect context

### ISSUE THREAD

**Issue by lucasconstantino** [netlify/cli#908]
https://github.com/netlify/cli/blob/d9756720205413ae771223098eb78cee71853338/src/commands/build/index.js#L31

**Comment by ehmicky** [comment]
Thanks @lucasconstantino for reporting this.

Don't hesitate to add more information when filing bugs, it helps us understand the problem.

For reference, the problem here is that the `--context` CLI flag is not passed from the CLI to `@netlify/build` due to the line of code referenced in the initial post.

**Comment by ehmicky** [comment]
Actually, the `--context` CLI flag does work properly. It is set inside [`cachedConfig`](https://github.com/netlify/cli/blob/d9756720205413ae771223098eb78cee71853338/src/commands/build/index.js#L26) at the [following line](https://github.com/netlify/cli/blob/d9756720205413ae771223098eb78cee71853338/src/utils/command.js#L80). We also have a [unit test](https://github.com/netlify/cli/blob/d9756720205413ae771223098eb78cee71853338/tests/build.test.js#L48).

@lucasconstantino Could you please describe your problem and steps to reproduce it? Thanks a lot.

**Comment by lucasconstantino** [comment]
Sorry for the noise. I'm just walking through the code debugging something related to local plugins. I'll share a better description if I can simulate the bug I have properly.

Thanks
