### ISSUE TITLE
Dev Command - Source headers overwriting user configured headers

### ISSUE THREAD

**Issue by sdn90** [netlify/cli#990]
**- Do you want to request a _feature_ or report a _bug_?**
Not sure if feature or bug

**- What is the current behavior?**
The source headers overwrite any headers configured in `_headers` or `netlify.toml`

**- If the current behavior is a bug, please provide the steps to reproduce.**
Using site generated by `jekyll new`. I think this should be reproducible with any static site generator that has a server which the CLI proxies to.

_headers
```
/
  Content-Type: some-mime-type
```

```
$ netlify dev
$ curl -i localhost:8888
```

**- What is the expected behavior?**
`Content-Type` header should be `some-mime-type`

**- Local Environment Information**

    OS: macOS 10.15.5
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
  Binaries:
    Node: 10.16.3 - /var/folders/tg/r5w4fb1s7lx6r8s3y5_6lqqh0000gn/T/yarn--1594942352128-0.2731175329792135/node
    Yarn: 1.22.4 - /var/folders/tg/r5w4fb1s7lx6r8s3y5_6lqqh0000gn/T/yarn--1594942352128-0.2731175329792135/yarn
    npm: 6.9.0 - ~/.asdf/installs/nodejs/10.16.3/bin/npm
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmGlobalPackages:
    netlify-cli: 2.58.0

netlify-cli/2.58.0 darwin-x64 node-v10.16.3

----
The problem is here:
https://github.com/netlify/cli/blob/5b6eff47a77796a67b5c59255c419a0bbbf88933/src/commands/dev/index.js#L140-L144

The headers set in `res.writeHead` will overwrite any previous set headers

**Comment by pccasto** [comment]
Issue appears to be with upstream package node-http-proxy, and the setHeader call, as mentioned here:
https://github.com/http-party/node-http-proxy/issues/1401

Seems like there are lots of open issues and pull requests against the node-http-proxy package, so it would be helpful if netlify handled this use case. The odds appear that it will not be fixed in that upstream package any time soon.

As it is, it is very challenging to develop / test certain header combinations using the dev cli. And the behavior will be different once deployed, because there is no originating server & proxying server in the production environment. The optimal behavior would be a switch to allow overriding or merging of headers.

From what I can see, from a quick revie, this like someone's solution on the node-http-proxy side, but I haven't tested it myself. It might form the basis for some code for handling this header merging or replacing logic at the netlify level. Or there might be better was to solve it (ymmv).
https://github.com/http-party/node-http-proxy/issues/1151

For others who are looking for work arounds.

I have been banging my head against this while trying to figure out how to set up cache control while testing in dev environment with Jekyll (Webrick) and netlify dev.  This is specific to the cache-control, but with a bit of sleuthing, the same type of change could be done to remove the content-type.

My current solution was to hack the jekyll-4.1.1\lib\jekyll\commands\serve\servlet.rb file to remove/comment out the default. I'll see about adding an issue or patch with that project based on this use case. Webrick is hard-coded to send out a Cache-Control that is very restrictive.

#### **`lib\jekyll\commands\serve\servlet.rb`**
``` ruby
class Servlet < WEBrick::HTTPServlet::FileHandler
        DEFAULTS = {
#          "Cache-Control" => "private, max-age=0, proxy-revalidate, " \
#           "no-store, no-cache, must-revalidate",
        }.freeze
```

Other things I tried was the below setting into _config.yml. That will cause Jekyll/Webrick to set cache-control to empty. But that still runs into the issue at the netlify proxy, where the the setHeader (in netlify => node-http-proxy call) won't even overwrite an empty string. (Note that this configuration is case sensitive...)

#### **`_config.yml`**
``` yaml
webrick:
  headers:
    Cache-Control: ""
```

I've also tried playing with a monkey patch in the _plugins directory, but those load before Webrick, so I'm not holding out hope for that as a solution.

**Comment by pccasto** [comment]
This only addresses part of the original reporter's issue (Cache-Control).
- I've opened a pull request on the Jekyll side: https://github.com/jekyll/jekyll/pull/8331
- In the meantime if anyone else needs to work with Cache-Control headers in `netlify dev` you can try adding this patch into your plugins directory: https://gist.github.com/pccasto/176329b389f46970a9d39be90a8a488d

**Comment by sarahetter** [comment]
Closing as stale. Please re-open if needed
